name: CI

on:
    push:
        branches:
            - main

jobs:
    check-lints:
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install Linters
              uses: dtolnay/rust-toolchain@stable
              with:
                components: rustfmt, clippy

            - name: Cache Cargo
              uses: Leafwing-Studios/cargo-cache@v1.1.0

            - name: Install alsa and udev
              run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev

            - name: Check
              run: cargo run -p ci -- lints
